services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=PASS123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=school_app
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db

  
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - db
      - adminer

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - db

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    logging:
      driver: "none"

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:PASS123@db:5432/school_app?sslmode=disable"
    depends_on:
      - db

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9101:9100
    depends_on:
      - db
      - prometheus

  docker:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - prometheus
