services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=PASS123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=school_app
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db

  
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - db
      - adminer
